#!/usr/bin/python3
""" routes '/' and '/hbnb' """
from flask import Flask

myapp = Flask(__name__)
from flask import Flask


@app.route('/', strict_slashes=False)
def fromRoot():
    return f'Hello HBNB!'

@app.route('/hbnb', strict_slashes=False)
def from_root_hbnb():
    return f'hbnb'


if __name__ == '__main__':
    myapp.run(host='0.0.0.0', port=5000)
